### ISSUE TITLE
display problems / height computation?

### ISSUE THREAD

**Issue by garyhooper** [emn178/jquery-stickit#26] opened 2016-12-20 19:44 UTC
When using stickit, all works well until scrolling to the bottom of the screen.  It looks like the height computation is incorrect, as the screen is flashing.

My usage is the simplest case, with an offset from the top of the screen:

  jQuery(document).ready(function(){
    jQuery("#programtoc").stickit({top: 120});
    jQuery("#programtocx > a").click(function(e) {
      // Prevent a page reload when a link is pressed
      e.preventDefault();
      // Call the scroll function
      goToByScrolling(jQuery(this).attr("id"));          
    });
  });

The problem page is https://s5.kinghooper.com/program/becoming-a-diabetes-educator-san-francisco-march-2017/.

Any suggestions?

Thanks!

**Comment by emn178** [comment] 2016-12-21 03:16
Thanks for report. This is caused by float element with percent width. It should be fixed in v0.2.11. Please try again.

**Comment by garyhooper** [comment] 2016-12-21 23:17
works great!  thank you!

**Closed** 2016-12-22 00:56 UTC
